### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Decapitater** [0xff01WasTaken/GrowthBot#1]
T

**Comment by 0xff01WasTaken** [comment]
does not work

**Comment by 0xff01WasTaken** [comment]
also totally forgot i had repository lol

**Comment by 0xff01WasTaken** [comment]
![image](https://user-images.githubusercontent.com/63504887/141410355-40257966-8692-442a-ac39-572bca57c1fd.png)

**Comment by Decapitater** [comment]
Use my name Decaptator

**Comment by Decapitater** [comment]
![IMG_20211112_100922.jpg](https://user-images.githubusercontent.com/72186879/141410531-f38c2960-c0c0-42d3-8556-5f13fff5433d.jpg)

**Comment by 0xff01WasTaken** [comment]
use where

**Comment by Decapitater** [comment]
Telegram ?

**Comment by 0xff01WasTaken** [comment]
i dont have a telegram account, do you have discord?

**Comment by Decapitater** [comment]
Ahh , wait i am making one

**Comment by 0xff01WasTaken** [comment]
cool, send me the tag once you are done

**Comment by Decapitater** [comment]
Decapitator#4149

**Comment by Decapitater** [comment]
@0xff01WasTaken

**Comment by 0xff01WasTaken** [comment]
check friend reqs

**Comment by 0xff01WasTaken** [comment]
@Decapitater

**Comment by Decapitater** [comment]
@0xff01WasTaken done
